version: '2'
services:
    studyshare-app:
        image: studyshare
            - studyshare-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/studyshare
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    studyshare-mariadb:
        extends:
            file: mariadb.yml
            service: studyshare-mariadb
